### ISSUE TITLE
GPS indicator always display

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#16]
![8DD07BD4-45FB-49F1-A6C4-7A0C97BF6B3C](https://user-images.githubusercontent.com/15531137/89114888-b2124e00-d4b3-11ea-92b3-144914352b43.jpeg)

As you can see, even my NiceBarX location icon not showing anything uses my GPS, but the GPS indicator keep displaying since I installed it :(

iPhoneX, iOS13.3, Checkra1n :)

**Comment by L1ghtmann** [comment]
If the GPS indicator does not go away try disabling "location based alerts" in system services and respringing your device

**Comment by CySxL** [comment]
Sure! Solved!
