### ISSUE TITLE
Feature request: central alignment 

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#17]
Please add an option or ability to center indicators  that are currently displaying.

For example: If only GPS indicator is being used then center it to middle of module(? ;  If GPS and Mic are being used put them both in the middle of center instead of always displaying GPS left and Camera right.

**Comment by CySxL** [comment]
Btw, it's okay for me now.

I adjust got the best setup on my device haha.

Shall I close this issue @UsrLightmann ?

**Comment by L1ghtmann** [comment]
Glad to hear it!

I've got it.
