### ISSUE TITLE
Not working in Facetime

### ISSUE THREAD

**Issue by OsamaMazhar** [UsrLightmann/Quorra#18]
Thanks for the update! Great work!

One issue, it doesn't show camera indicator in Facetime, in calls and also when we just launch the app and we have a blurred stream from the camera. iOS 13.5.1 checkra1n iPhone6s.

**Comment by L1ghtmann** [comment]
Osama,

I am looking into a better method for detecting camera usage since the current one isn't very reliable. 

Thank you for bringing this to my attention!


Lightmann

**Comment by L1ghtmann** [comment]
Part of a larger issue. See issue #21.
