### ISSUE TITLE
Bug report : Procrastination

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#19]
Had tested Quorra on some third party apps that need GPS location and Camera, finding out that the dots would procrastinate for a few seconds (about 20 seconds), also didn't disappear after not using those privacy needed functions.

**Comment by CySxL** [comment]
Quick conclusion : With system apps (stock camera) and stock features (siri) launched, Quorra will display dots like expected immediately, but seems like not really smooth in third party apps tho.

**Comment by L1ghtmann** [comment]
CySxL,

Are there any apps where this "procrastination" is particularly apparent?

The only indicator that I could see being delayed would be the camera because of my choice of methods, which I am looking into revising due to reliability issues. 


Lightmann

**Comment by CySxL** [comment]
oh! thanks for replying!

For my observation the app "Line" and "Instagram" , which both are communication apps, have the procrastination of Quorra disappearing.

For example If I use camera feature of Instagram/Line/Facebook messenger/Telegram/Facebook/Discord/Dcard (almost every third party apps needing camera access), the green dot would show up correctly and immediately, but after I closing the camera window the green dot is still there displaying.

And "Line" would always displays blue dot after I share my location to friends and go back to text windows. Also blue dot would pop up every time I launch "Line".

The only app which is smoothly displaying green dot is Youtube, green dot disappear immediately after closing camera function.

FYI, the bundle id of "Line" : jp.naver.line ;  bundle id of "Dcard" : com.dcard.app.Dcard

**Comment by L1ghtmann** [comment]
CySxL,

Okay, thanks for letting me know. It seems the current method for the camera is not widely used in 3rd party apps and the location method falters occasionally. I will look into fixing both.


Lightmann

**Comment by L1ghtmann** [comment]
Part of a larger issue. See issue #21.
