### ISSUE TITLE
SneakyCam compatibility

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#20]
After using SneakyCam by SparkDev, the green dot always displays. 

Only a respring can dismiss it.

**Comment by L1ghtmann** [comment]
Related to my camera detection method. Will look into a new, more sound method.

**Comment by CySxL** [comment]
Thanks man :)

And one more little question, would the persistence dots cause oled screen burned out ?

**Comment by L1ghtmann** [comment]
Part of a larger issue. See issue #21.
