### ISSUE TITLE
Spotify issue

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#22]
After updating to 1.0.5, I've noticed that when playing songs with Spotify app Quorra would display a Mic indicator which is ok. But somehow Spotify will be suspended/freezing (can't play music) after launching.

Need twice and more respring to make it works again.

Tried disabling Quorra wIth iCleaner Pro and tested again, and Spotify worked normally tho.

My Info: iPhoneX, iOS13.3, Checkra1n
Spotify version : 8.5.72

Edit: Might be conflicting with Spotilife, but previously version 1.0.3 doesn't have this issue.

**Comment by CySxL** [comment]
Update:
Try upgrade form 1.0.3 to 1.0.5 again and LDrestart.

Spotify works fine now, would put some new info here.

**Comment by CySxL** [comment]
Edit2: After a relaunch of Spotify, the issue comes out again : Spotify totally freezing and can't do anything on it .

Here is the freezing video demo:
https://streamable.com/ugv2yc

FYI: in 1.0.5 Quorra will show MIC 🎙 indicator while Spotify is playing music, however 1.0.3 Quorra wouldn't.

Edit: I'm using Harbor 3 's dock app running indicator, can observe that with Quorra 1.0.5, after closing Spotify from app switcher it will remain running about 10 - 15 seconds until actually being terminated.

**Comment by IvanKulagin** [comment]
Can confirm on this. Also, when I reopened Spotify few time and it didn't give me any result, I tried to reboot userspace, but it stuck on spinning circle and then the phone rebooted. I tried to jailbreak again but it kept crashing. The only thing that helped was jailbreaking without tweaks, then deleting Quorra, then re-jailbreaking.

**Comment by CySxL** [comment]
@IvanKulagin Wanna know that do u use Spotilife ?

**Comment by IvanKulagin** [comment]
@CySxL No, I have Premium

**Comment by CySxL** [comment]
@IvanKulagin Thanks for the replying.
So seems like it just an issue related to Spotify itself.

Temporary solution: use Choicy to disable Quorra in Spotify.

**Comment by L1ghtmann** [comment]
Larger issue. Closing in favor of #26.
