### ISSUE TITLE
Kalm compatibility

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#23]
I'm using Kalm by ubik with weather display enabled. 

While every time I swipe down notification center and the Kalm weather display is refreshing itself, the blue indicator of Quorra shows up which is great, but after the Kalm weather feature ends refreshing, the blue indicator would remain there.

Except for this issue, all the other indicators works flawlessly in third-party apps !! Also SneakyCam too !! Thanks for the great update :)

My info: iPhoneX, iOS13.3, Checkra1n

**Comment by L1ghtmann** [comment]
Glad the other indicators are more reliable!

Closing this issue in favor of #25 which is more broad.
