### ISSUE TITLE
landscape duplicate

### ISSUE THREAD

**Issue by CySxL** [UsrLightmann/Quorra#24]
![414F7D05-6FAE-40F6-A551-6F978022AA4C](https://user-images.githubusercontent.com/15531137/98056487-0b0acd00-1e7b-11eb-96ea-4d68d252ae0d.jpeg)

I guess the blue indicator is from [[Kalm]]

The orange indicator is from this game itself 🤣🤣

**Comment by L1ghtmann** [comment]
Closing this issue in favor of #25.
