### ISSUE TITLE
ios 12?

### ISSUE THREAD

**Issue by mailinglists35** [UsrLightmann/Quorra#28]
I cannot upgrade to ios 13.
is it technically doable for ios 12? I am on 12.4

thank you

**Comment by L1ghtmann** [comment]
It is possible, yes. Once I get the last few issues ironed out to the best of my ability I can look into it.

**Comment by mailinglists35** [comment]
lovely, can't wait, thank you! :-)

**Comment by L1ghtmann** [comment]
Okay, have a test build ready. Would you be willing to try it out? If so, please shoot me an email (click the mail icon on my [repo](https://usrlightmann.github.io)).

**Comment by L1ghtmann** [comment]
iOS 12 support added with v1.0.7

**Comment by mailinglists35** [comment]
thank you for the email build. I wasn't able to test it as quickly as you but the latest released version works!

cheers! 🙂
