### ISSUE TITLE
Not working as of version 1.0.6.1

### ISSUE THREAD

**Issue by chrismonster13** [UsrLightmann/Quorra#29]
Unfortunately the tweak has stopped working completely on the most recent version with the change log of “code cleanup” 

If I can provide you with more information, please don’t hesitate to ask 😁

**Comment by L1ghtmann** [comment]
A fix will be coming soon! Sorry about that.

**Comment by chrismonster13** [comment]
> A fix will be coming soon! Sorry about that. 

It's totally ok! I know these things can happen lol. We appreciate your work on this 😁

**Comment by L1ghtmann** [comment]
Please let me know if I managed to resolve this with the latest version (v1.0.7)

**Comment by chrismonster13** [comment]
> Please let me know if I managed to resolve this with the latest version (v1.0.7)

Seems to work much better now. I just asked Siri the weather and both dots showed at once for the microphone and location. Seems good so far! Thanks for the fix!
