### ISSUE TITLE
Black font in YouTube’s status bar

### ISSUE THREAD

**Issue by joseclark95** [UsrLightmann/Quorra#3]
Hello, nice tweak, working fine but I encountered this visual error, so far I’ve only found it in the YouTube app, the font turns black instead of the normal white when the tweak is on, fixes it disabling it with iCleaner.

Thanks

**Comment by L1ghtmann** [comment]
Okay, thanks for letting me know. Will take a look at this once the bugs have been sorted

**Comment by L1ghtmann** [comment]
I just took a look and can't seem to replicate this on my device. If anyone else can reliably replicate this please let me know.

**Comment by joseclark95** [comment]
Can I send you a ss of the before and after?
