### ISSUE TITLE
feature suggestion: produce a log file

### ISSUE THREAD

**Issue by mailinglists35** [UsrLightmann/Quorra#30]
I can see the dot if I am looking at the phone.

But let's think like a spy: do I want to spy the microphone if the phone is in victim's hand? Probably not, because I could draw attention.

Instead I would patiently wait until the phone is laying face down on solid desk/table.

There are already apps that abuse randomly and repeatedly trying to read the clipboard when the app is in background (medicus.ai from App Store) - thanks to ConfirmPasteboard author I can deny that. What would prevent them from also using the microphone? Is that technically possible?

Anyway, that was just an example when the user might not be paying attention to the screen. 

So I am wondering if it's technically possible to catch the name of the app, and if not, even a simple timestamped log would be useful, like:

date time appid microphone started
date time appid front camera started
dste time appid microphone stopped

Thank you!

**Comment by L1ghtmann** [comment]
May do a log of sorts in prefs with a scrollable collectionview w 'X' recent calls/uses or, more likely, will add an option for usage notifications which will be available in the Notification Center for later viewing with the app (icon), usage type, and timestamp.

**Comment by UsrLightmann** [comment]
Hey! I've got the usage notifications working. Would you be willing to try it out? If so, could you shoot me an email (mail icon on [my repo](https://usrlightmann.github.io)). Thanks!

**Comment by L1ghtmann** [comment]
While I was working on v1.0.8, I decided to take a jab at usage notifications and have some things to report:

Though it worked, it did not work well enough for me to feel comfortable including it in the release build. 

After coming to this conclusion, I gave some thought to alternatives and none seemed suitable: Quorra is already present in the status bar so I doesn't make sense to add anything else there, the CC isn't feasible (given the number of custom CC tweaks), notifications didn't work well, and the only other thing I could think of was a log file, but that is too out-of-the-way for the average user. 

After finishing up this release, I've decided to take a _likely_ permanent break from working on Quorra. In the event that a solution comes to me, I may take another look at implementing this. If not, it will likely stay shelved permanently. Just thought I'd let you know, so you weren't left hanging.

**Comment by mailinglists35** [comment]
>permanent break from working on Quorra

thank you for your work, Quorra it's very valuable for me! good luck!

**Comment by L1ghtmann** [comment]
Hey, so I had something come to me and decided to give one last crack at the notifications. The results are pretty promising, I think. If you'd like to try it, please shoot me an email. If all goes well, I hope to have it up on the repo sometime early this week.

**Comment by L1ghtmann** [comment]
Option for a LS Notification Log added in v1.1.0

**Comment by mailinglists35** [comment]
Thank you very much. I apologise I didn't find much time to complete the testing.

**Comment by L1ghtmann** [comment]
> Thank you very much. I apologise I didn't find much time to complete the testing.

No worries!
