### ISSUE TITLE
bug: no visible dots on iPad11,3 iOS 13.5

### ISSUE THREAD

**Issue by mailinglists35** [UsrLightmann/Quorra#31]
The app installs okay, I checked the settings to make sure the toggle is enabled.

I can provide ssh over teamviewer if it helps debugging.

Thanks!

**Comment by L1ghtmann** [comment]
Hey,

So you've confirmed that _none_ of the indicators appear _at all_? 

If so, have you tried reinstalling? LDRestart? 

Quorra, to the best of my knowledge, has no conflicts, so I'm honestly unsure why it's not working for you.

**Comment by mailinglists35** [comment]
yes, even reboot

![image](https://user-images.githubusercontent.com/2054302/102819271-d5df1d80-43db-11eb-993a-ec3ed2de6aa6.png)

**Comment by mailinglists35** [comment]
list of tweaks and configuration page![image](https://user-images.githubusercontent.com/2054302/102819393-0fb02400-43dc-11eb-819d-8ce4473119ca.png)

**Comment by L1ghtmann** [comment]
Okay, nothing seems out of place, like you said. 

My current method for detecting the camera relies on the flash unit being available or not and your device doesn't seem to have a flash unit, so that would explain the missing camera indicator. 

As for the others, I'm honestly at a loss. My only other idea would be to reinstall your JB's respective bootstrap (substrate, substitute, or libhooker)

**Comment by mailinglists35** [comment]
hey, sorry I found a solution but forgot to update the issue.
the dots (all three) appear if I enter manual offsets like 100,100. will have to try and find the right values to send the dots to the edge somewhere 

cheers

**Comment by L1ghtmann** [comment]
Glad you found a fix! 

So with the offsets set to default (empty) the dots are hidden on your device?

**Comment by mailinglists35** [comment]
> So with the offsets set to default (empty) the dots are hidden on your device? 

yes. no single dot anywhere. turned brightness to max trying to find the dots... nothing! :-)

**Comment by L1ghtmann** [comment]
Okay. I'll look into fixing that in the future. Thanks for bringing it to my attention!
