### ISSUE TITLE
Crashes after upgrade from 1.08 to 1.11

### ISSUE THREAD

**Issue by MBehr2** [UsrLightmann/Quorra#35]
https://ghostbin.co/paste/sps3c

**Comment by chrismonster13** [comment]
Same issue for me unfortunately. I'm sorry I know how much you've worked on this lol 

https://ghostbin.com/paste/IoEWc

**Comment by L1ghtmann** [comment]
Hey! Thanks for providing crash logs.

I switched the code from MRYIPC over to rocketbootstrap and it seems to have resolved the crashing. Would you be willing to try it out? If so, please shoot me an email (mail icon on my repo https://usrlightmann.github.io). Thanks in advance!

**Comment by L1ghtmann** [comment]
Crashing fixed in v1.1.1. Thanks again for your help testing!

**Comment by MBehr2** [comment]
Works like a charm! Kudos, and thank you for all your hard work. Cheers 
    On Friday, February 12, 2021, 01:18:47 PM EST, Lightmann <notifications@github.com> wrote:  
 
 


Crashing fixed in v1.1.1. Thanks again for your help testing!
