### ISSUE TITLE
Add ability to allow/deny apps.

### ISSUE THREAD

**Issue by Absolucy** [UsrLightmann/Quorra#4]
A blacklist/whitelist for apps to care about in settings would be nice. For example, ignoring System Services or Snapchat.

**Comment by L1ghtmann** [comment]
Following the recent release, I've decided to take a _likely_ permanent break from working on Quorra. As such, is it unlikely that I will add this feature any time soon, so I am closing this issue. If I decide to pick it up again, I may take a look at adding this. No promises though.
