### ISSUE TITLE
In-App purchases break

### ISSUE THREAD

**Issue by OsamaMazhar** [UsrLightmann/Quorra#5]
This breaks in-app purchases and those apps crash when opened. Reinstalling the app makes it open the app but restoring in-app purchases stuck and then app start crashing. Tested by uninstalling and reinstalling the tweak. iPhone  6s, 13.5.1, chekra1n jailbreak, app crashed Focos.

**Comment by L1ghtmann** [comment]
Okay. noted. I have made a new issue that fits this description as well as others that have been reported
