### ISSUE TITLE
GPS Indicator won't go away for some users

### ISSUE THREAD

**Issue by L1ghtmann** [UsrLightmann/Quorra#7]
Current Theory: Dependent on user's location service settings; not a tweak issue

**Comment by vismittu** [comment]
I have this issue even when i turned off the location services.

**Comment by hessen25** [comment]
I have the same issue. Also with the camera and microphone indicators, i have to quit the app then open it again for the indicator to disappear.

**Comment by Absolucy** [comment]
https://github.com/UsrLightmann/Quorra/issues/4 could possibly solve this.

**Comment by L1ghtmann** [comment]
TO FIX THIS DISABLE "LOCATION BASED ALERTS" IN SYSTEM SERVICES AND RESPRING
