### ISSUE TITLE
Apps Crash

### ISSUE THREAD

**Issue by L1ghtmann** [UsrLightmann/Quorra#9]
Some apps require main thread and others don't

causes two separate errors; need way to check and pick thread accordingly or simply not require main thread (change method)

**Comment by larssieboy18** [comment]
Whatsapp crashes when using Quorra (when starting a video call). Same goes for Cr4shed when trying to export a crash file to files.
Link to crash files: https://pastebin.com/KgieUsNX and https://pastebin.com/hApJVUV1

If you need any help testing or something, let me know!
